// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnaym9DiJOj-UjLY48n7nWpxSTl8KIKQg',
    appId: '1:548687720012:web:20248f87fd1b65183dcee9',
    messagingSenderId: '548687720012',
    projectId: 'spendx-ae320',
    authDomain: 'spendx-ae320.firebaseapp.com',
    storageBucket: 'spendx-ae320.firebasestorage.app',
    measurementId: 'G-NTYPWB3693',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuGd7TtkqTIvAcNzcNdXo6OIphQkX9AaM',
    appId: '1:548687720012:android:d30f11bfda0bb2453dcee9',
    messagingSenderId: '548687720012',
    projectId: 'spendx-ae320',
    storageBucket: 'spendx-ae320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVsdwlATNcQiKjwwR-4hl8_tZ0NOLnrIU',
    appId: '1:548687720012:ios:f64896e2242b04d73dcee9',
    messagingSenderId: '548687720012',
    projectId: 'spendx-ae320',
    storageBucket: 'spendx-ae320.firebasestorage.app',
    iosBundleId: 'com.example.smartspend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVsdwlATNcQiKjwwR-4hl8_tZ0NOLnrIU',
    appId: '1:548687720012:ios:f64896e2242b04d73dcee9',
    messagingSenderId: '548687720012',
    projectId: 'spendx-ae320',
    storageBucket: 'spendx-ae320.firebasestorage.app',
    iosBundleId: 'com.example.smartspend',
  );
}
